kind: Service
metadata:
  name: microservicio-app-service
  namespace: ns-app-dev
  labels:
    app: microservicio-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: microservicio-app
# Source: microservicio-base/templates/deployment.yaml
apiVersion: apps/v1
