{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.environment }}
  annotations:
    # AWS Load Balancer Controller annotations
    {{- if .Values.ingress.group.enabled }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.annotations.awsGroupName | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.annotations.awsListenPorts | quote }}
    {{- end }}

    {{- if eq .Values.ingress.className "alb" }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.annotations.awsTargetType | default "ip" }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.annotations.awsBackendProtocol | default "HTTP" }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.ingress.annotations.awsSuccessCodes | default "200" }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.annotations.awsHealthcheckPath | default "/actuator/health" }}
    {{- end }}

    # Custom annotations adicionales
    {{- range $key, $value := .Values.ingress.annotations.custom }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    {{- range .Values.ingress.rules }}
    - {{- if .host }}
      host: {{ .host }}
      {{- end }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ $.Values.appName }}-service
              port:
                number: {{ .servicePort }}
        {{- end }}
    {{- end }}
{{- end }}
