{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.environment }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.serviceAccount.annotations.irsaRoleArn }}
    # AWS IRSA (IAM Roles for Service Accounts)
    # Permite que el pod asuma un IAM role de AWS sin credenciales
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.annotations.irsaRoleArn }}
    {{- end }}

    {{- range $key, $value := .Values.serviceAccount.annotations.custom }}
    # Custom annotations
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
